config/routes.rb
Rails.application.routes.draw do
  
  resources :tasks, only: [:index, :show] do
    resources :lists, only: [:create, :destroy]
  end

  root 'tasks#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :lists
  has_many :users, through: :lists
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
  has_many :tasks, through: :lists

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    @task = Task.find(params[:task_id])
    @list = List.new(task: @task, user: current_user)
    
    if @list.save
      redirect_to root_path, notice: 'Tarea completada'
    else
      redirect_to root_path, alert: 'Acción no completada'
    end
  end

  def destroy
    # toma todos los valores con "take"
    @list = List.where(user_id: current_user.id, task_id: params[:task_id]).take

    if @list.destroy
      redirect_to root_path, notice: 'Tarea marcada como No Completada'
    else
      redirect_to root_path, alert: 'Acción no completada'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.all
    @task = Task.find(params[:id])
    @top5 = @task.lists.order(:created_at).limit(5)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  # Método Helper para saber si la tarea fue completada o no
  def completed?(task, user)
    task.users.exists?(user.id) # Busca si en la tarea, existe un usuario con el id de usuario actual.
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#">Bienvenido <%= current_user.email %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-info">Tareas completadas: <%= current_user.tasks.count %> / <%= @tasks.count %></a>
          </li>
        <% end %>
      </ul>
      
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="btn btn-outline-danger" href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="btn btn-outline-primary mx-2 my-1" href="<%= new_user_session_path %>">Sign in</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-primary mx-2 my-1" href="<%= new_user_registration_path %>">Sign up</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actividad38</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/tasks/index.html.erb
<div class="row mt-3">
  <% @tasks.each_slice(3) do |row| %>
    <% row.each do |task| %>
      <div class="col-sm-12 col-md-4 col-lg-4">
        <div class="card">
          <% if completed?(task, current_user) %>
            <%= link_to (image_tag task.image, class: 'card-img-top img-fluid img-not-completed'), task_path(task) %>
          <% else %>
            <%= link_to (image_tag task.image, class: 'card-img-top img-fluid'), task_path(task) %>
          <% end %>
          <div class="card-body text-center">
            <h5 class="card-title"><%= task.title %></h5>
            <p class="card-text"><%= task.description %></p>
            <% if completed?(task, current_user) %>
              <a href="<%= task_list_path(task, task.lists) %>" data-method="delete" class="btn btn-success">
                Completado
              </a>
            <% else %>
              <a href="<%= task_lists_path(task) %>" data-method="post" class="btn btn-primary">
                No completado
              </a>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="w-100" style="margin-top: 20px"></div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="text-center col-sm-12 col-md-12 col-lg-12">
    <h2><%= @task.title %></h2>
    <p><%= @task.description %></p>
  </div>

  <div class="text-center col-sm-12 col-md-12 col-lg-12">
    <% if @task.users.count == 0 %>
      <h5 class="alert alert-danger">Nadie ha completado está tarea aún.</h5>
    <% else %>
      <h5 class="text-info">Los siguientes usuarios han completado esta tarea:</h5>
      <ul class="list-group">
        <% @task.users.each do |user| %>
          <li class="list-group-item"><%= user.email %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="text-center col-sm-12 col-md-12 col-lg-12 mt-3">
    <h5 class="text-info">Primeras 5 personas en completar esta tarea:</h5>
    
    <ul class="list-group">
      <% @top5.each do |list| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-12 col-md-2 col-lg-2">
              <%= image_tag list.user.image, class: 'imageTopFive img-thumbnail"'%>
            </div>
            <div class="col-sm-12 col-md-10 col-lg-10">
              <p>Usuario: <%= list.user.name %></p>
              <p>Tarea realizada: <%= list.created_at.localtime.to_formatted_s(:long) %></p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>